#!/bin/bash
# Build "Survey Viewer.app" -- a double-clickable launcher for the local viewer.
#
#   ./viewer/tools/make-mac-app.sh [--out DIR] [--name NAME] [--port N]
#
# The app is NOT bound to any repository. At launch it resolves which repo to
# serve (remembered > ask), then runs THAT repo's viewer-launcher.sh. So one app
# serves any number of clones, and moving a repo costs a re-pick, not a rebuild.
#
# The bundle carries exactly one copied file -- Resources/pick-repo.sh, the
# bootstrap that runs before a repo is known. Everything else executes from the
# selected repo, so viewer and launcher edits still need no rebuild. Re-run this
# script only to refresh that bootstrap or change the baked-in port.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VIEWER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PICKER_SRC="$SCRIPT_DIR/pick-repo.sh"

OUT_DIR="$HOME/Applications"
APP_NAME="Survey Viewer"
PORT=""

while [ $# -gt 0 ]; do
  case "$1" in
    --out)  OUT_DIR="$2"; shift 2 ;;
    --name) APP_NAME="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    -h|--help) sed -n '2,14p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

[ -f "$PICKER_SRC" ] || { echo "missing bootstrap: $PICKER_SRC" >&2; exit 1; }

APP="$OUT_DIR/$APP_NAME.app"
EXE_NAME="$(echo "$APP_NAME" | tr -d ' ')"

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# --- Info.plist ---------------------------------------------------------------
# LSUIElement makes this an accessory app: it starts the server, opens the window
# and exits, without leaving a stale Dock icon behind. Failures surface as a
# Finder alert instead (VIEWER_GUI=1 in the shim), since an accessory app has no
# console the user would ever see.
cat >"$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>local.viewer.launcher</string>
  <key>CFBundleExecutable</key><string>$EXE_NAME</string>
  <key>CFBundleIconFile</key><string>appicon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.1</string>
  <key>CFBundleVersion</key><string>2</string>
  <key>LSUIElement</key><true/>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# --- bootstrap copy -----------------------------------------------------------
cp "$PICKER_SRC" "$APP/Contents/Resources/pick-repo.sh"
chmod +x "$APP/Contents/Resources/pick-repo.sh"

# --- executable shim ----------------------------------------------------------
SHIM="$APP/Contents/MacOS/$EXE_NAME"
cat >"$SHIM" <<'SHIMEOF'
#!/bin/bash
# Generated by viewer/tools/make-mac-app.sh -- do not edit.
# Resolves a repository, then hands off to that repo's own launcher.
set -uo pipefail

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
PICKER="$SELF_DIR/../Resources/pick-repo.sh"
VIEWER_GUI="${VIEWER_GUI:-1}"; export VIEWER_GUI

alert() {
  printf '%b\n' "$1" >&2
  [ "$VIEWER_GUI" = "1" ] &&
    /usr/bin/osascript -e "display alert \"Survey Viewer\" message \"$1\" as critical" >/dev/null 2>&1
  exit 1
}

[ -x "$PICKER" ] || alert "Survey Viewer is missing its bootstrap:\n\n$PICKER\n\nRebuild the app:\n    ./viewer/tools/make-mac-app.sh"

# Holding Option at launch opens the recents menu instead of going straight into
# the remembered repo -- the standard macOS "let me choose" gesture. 524288 is
# NSEventModifierFlagOption. --pick does the same from a terminal.
MODE=resolve
if [ "${1:-}" = "--pick" ]; then
  MODE=choose
elif [ "$VIEWER_GUI" = "1" ] &&
     [ "$(/usr/bin/osascript -l JavaScript \
            -e 'ObjC.import("AppKit"); String(($.NSEvent.modifierFlags & 524288) ? 1 : 0)' \
          2>/dev/null)" = "1" ]; then
  MODE=choose
fi

REPO="$(/bin/bash "$PICKER" "$MODE")" || exit 1
# Empty means the user cancelled the dialog. That is a choice, not a failure --
# exit quietly rather than alerting them about something they just declined.
[ -n "$REPO" ] || exit 0

LAUNCHER="$REPO/viewer/tools/viewer-launcher.sh"
[ -x "$LAUNCHER" ] || alert "That repository has no viewer launcher:\n\n$LAUNCHER\n\nHold Option while launching to pick a different repository."

exec /bin/bash "$LAUNCHER" start @@PORTARGS@@
SHIMEOF

if [ -n "$PORT" ]; then
  /usr/bin/sed -i '' "s|@@PORTARGS@@|-p $PORT|" "$SHIM"
else
  /usr/bin/sed -i '' "s| @@PORTARGS@@||" "$SHIM"
fi
chmod +x "$SHIM"

# --- icon ---------------------------------------------------------------------
# Reuse the PWA icon so the launcher, the installed web app and the browser tab
# all show the same mark.
SRC_ICON="$VIEWER_DIR/icons/icon-512.png"
if [ -f "$SRC_ICON" ] && command -v iconutil >/dev/null 2>&1; then
  ICONSET="$(mktemp -d)/appicon.iconset"
  mkdir -p "$ICONSET"
  for spec in "16 16x16" "32 16x16@2x" "32 32x32" "64 32x32@2x" "128 128x128" \
              "256 128x128@2x" "256 256x256" "512 256x256@2x" "512 512x512"; do
    px="${spec%% *}"; name="${spec##* }"
    sips -z "$px" "$px" "$SRC_ICON" --out "$ICONSET/icon_$name.png" >/dev/null 2>&1 || true
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/appicon.icns" >/dev/null 2>&1 \
    || echo "note: icon conversion failed; the app will use the generic icon" >&2
  rm -rf "$(dirname "$ICONSET")"
else
  echo "note: no source icon or iconutil; the app will use the generic icon" >&2
fi

# --- ad-hoc sign --------------------------------------------------------------
# Not for distribution -- it just stops macOS re-prompting about a modified
# bundle each time it is rebuilt. Non-fatal if it fails.
if command -v codesign >/dev/null 2>&1; then
  codesign --force --sign - "$APP" >/dev/null 2>&1 || true
fi

# Refresh the Launch Services registration so the new icon shows immediately.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
  -f "$APP" >/dev/null 2>&1 || true

echo "built: $APP"
echo "  port: ${PORT:-3000 (default)}"
echo "  repo: chosen at launch (not baked in)"
echo
echo "Double-click to open the remembered repo; hold Option to pick another."
echo "Recents:  $SCRIPT_DIR/pick-repo.sh list"
echo "Stop:     <repo>/viewer/tools/viewer-launcher.sh stop"
